# Generated by Django 6.1.1 on 2026-09-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('platform', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolving', 'Resolving'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=50)),
                ('progress_percent', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
